### ISSUE TITLE
zookeeper_1              | /docker-entrypoint.sh: line 105: /zookeeper/conf/zoo.cfg: Permission denied

### ISSUE THREAD

**Issue by mvj3** [debezium/docker-images#8]
I use docker-compose to start zookeeper in a cluster mode, here's my yaml file

```yaml
zookeeper:
  image: debezium/zookeeper:0.1
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    - SERVER_COUNT=3
```

After I start it, I met below error,

```text
zookeeper_1              | Starting up in clustered mode
zookeeper_1              | /docker-entrypoint.sh: line 105: /zookeeper/conf/zoo.cfg: Permission denied
docker_zookeeper_1 exited with code 1
```
